name: mood_calendar
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  typewritertext: ^1.8.0
  rive: ^0.9.1
  dropdownfield2: ^1.0.7
  google_nav_bar: ^5.0.6
  http: ^0.13.5
  liquid_pull_to_refresh: ^3.0.1
  expandable_text: ^2.3.0
  flutter_slidable: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  flutter_heatmap_calendar: ^1.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - images/
